version = 0.1
[default.deploy.parameters]
stack_name = "VocabFinder"
resolve_s3 = true
s3_prefix = "VocabFinder"
region = "ap-northeast-1"
profile = "MyAWSWorker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
